### ISSUE TITLE
twilio requires phone numbers to begin with a + as per ITU E.164

### ISSUE THREAD

**Issue by marchharesoftware** [GluuFederation/casa#138]
When I use the Twilio CASA plugin to verify a phone number outside of USA I get:

```
16-06 01:52:01.728 ERROR [qtp534906248-57] plugins.authnmethod.service.TwilioMobilePhoneService TwilioMobilePhoneService.java:85- No message was sent, error was: The 'To' number 44XXXXXXXXXX is not a valid phone number.
16-06 02:00:36.514 ERROR [qtp534906248-17] plugins.authnmethod.service.TwilioMobilePhoneService TwilioMobilePhoneService.java:85- No message was sent, error was: The 'To' number 61XXXXXXXXX is not a valid phone number.
```

This has been reported by me and others here:
https://support.gluu.org/installation/9166/casa-twilio-mobile-registration-not-valid-number/

The error is described by twilio here:
https://www.twilio.com/docs/api/errors/21211

The e164 format is described here:
https://www.twilio.com/docs/glossary/what-e164

It clearly states: the format must be a number up to fifteen digits in length starting with a ‘+’

The 'number' gluu casa is providing to the twilio API does not start with a '+' and therefore is invalid.

The code is [here](https://github.com/GluuFederation/casa/blob/version_4.2.3/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/TwilioMobilePhoneService.java#L62):

Please provide a fix for 4.2.3 (the current stable release)

**Comment by jgomer2001** [comment]
Hi @marchharesoftware 

Thanks for reporting this. Not only can we send messages to US numbers without the `+` but also to some other countries. That explains why we didn't catch the problem earlier.

Today I made attempts with people from locations we never tried in the past and despite there were no errors in logs (messages appeared as *queued*) recipients were not getting the messages. Prepending with `+` solved it.

We can't provide fixes for already released versions to community users. You'll have to wait for the upcoming (4.3) or try to figure out how to patch your current version based on the commits that will appear here which will be obvious (adding the plus sign).

I'll add a comment to this issue when a new casa 4.3-snapshot war is available (that includes the fix) so that you can take the specific java class and patch your installation.

**Comment by jgomer2001** [comment]
...and regarding `The 'To' number 44XXXXXXXXXX is not a valid phone number` I don't have numbers to replicate

**Comment by marchharesoftware** [comment]
Thanks!

Can you provide a list of the country codes you have found that do NOT require the + prefix?  It may be helpful for twilio... I have an open bug with twilio about the inconsistent handling of +...

Eventually we want to build gluu ourselves from source rather than rely on the releases - this will mean (in theory) we can fix bugs ourselves and provide patches to you.  But for the initial implementation we wanted to go with a 'known good' distribution.  This probably won't happen until later this year.

I did see the developer guide for CASA that included how to develop an authentication plugin, and wondered if it's possible to 'clone' the twilio_sms plugin - make this code changes and disable from the 'standard' plugin then enable the 'custom' plugin.  So a baby step of switching from the binary distribution to the source distribution.  I'm assuming since its a plugin, we don't have to have the whole application source code building just to build this one part?
https://gluu.org/docs/casa/developer/

Any hints?

Eclipse on Ubuntu?

A bit like this:
https://gluu.org/docs/gluu-server/4.2/developer-guide/oxtrust-eclipse/

**Comment by jgomer2001** [comment]
It is totally feasible to write an authentication plugin in order to override one or more of the authenticacion methods bundled OOTB in Casa, also you don't need to compile any code except yours, however writing plugins has an associated learning curve. Particularly authentication plugins require more work than regular plugins.

After some reading, developers start writing plugins by example: along with developer docs we offer a number of [sample plugins](https://github.com/GluuFederation/casa/tree/version_4.2.3/plugins/samples) for this purpose. One usually ends up reading existing Casa code trying to mimick UI and behaviors already there.

We don't offer instructions targetted at any specific development environment. The oxtrust guide you referenced is extremely outdated. Use it at your own risk.

> Can you provide a list of the country codes

I can only remember Moldova, Colombia, United States.

**Comment by jgomer2001** [comment]
A 4.3 snapshot war is available [here](https://ox.gluu.org/maven/org/gluu/casa/4.3.0-SNAPSHOT/). Do not try to replace your existing 4.2.3 war with this one. It's not safe.

**Comment by marchharesoftware** [comment]
I got some more feedback from Twilio which may be of interest.

Basically they are saying - thanks for reporting it, but we can't reproduce the bug using their latest SDK.  With their 8.15.0 SDK they can send texts/SMS with or without the + prefix to the countries I nominated.

Today I don't have the time to write my own test to verify that, but it's interesting.

I did see that my install has /opt/gluu/jetty/oxauth/custom/libs/twilio-7.17.0.jar, which seemed a bit old, so I tried upgrading it to twilio-7.17.6.jar but then I couldn't get gluu to boot, so I rolled back that change.  With further experience of Gluu - I now wonder if those two events were not related, and that an upgrade of that JAR is warranted.

Twilio support pointed out that the Twilio dependancy for Casa seems to refer to SDK 7.47.1 - https://github.com/GluuFederation/casa/blob/version_4.2.3/app/pom.xml#:~:text=<version>7.47.1</version>
**Twilio SDK Version: ** https://mvnrepository.com/artifact/com.twilio.sdk/twilio

So I'm even more confused - why did I find 7.17.0 JAR when the SDK used in build was 7.47.1.

So my question is:  Is it OK to replace the included twilio-7.17.0.jar with twilio-8.14.0.jar ?  Seems like a lot of versions in between there...  I could try some builds in the 7.x series of course.

Or I could phrase the question the other way - is there a particular reason for shipping that particular Twilio JAR and/or building against that particular Twilio SDK?

I have asked twilio if they are aware of a particular version of the JAR that fixes this particular bug - ie: what was their bug number/release note...

As always, any help appreciated!

**Comment by marchharesoftware** [comment]
OK - I successfully upgraded the twilio JAR to 8.15.0 and the error still occurs.  I've updated the twilio support case, and I'll advise here if they say anything helpful

```
cd /opt/gluu/jetty/oxauth/custom/libs
mkdir ext
rm twilio-7.17.0.jar
curl --output twilio-7.47.1.jar  https://repo1.maven.org/maven2/com/twilio/sdk/twilio/7.47.1/twilio-7.47.1.jar
curl --output twilio-7.17.0.jar  https://repo1.maven.org/maven2/com/twilio/sdk/twilio/7.17.0/twilio-7.17.0.jar
curl --output twilio-8.15.0.jar  https://repo1.maven.org/maven2/com/twilio/sdk/twilio/8.15.0/twilio-8.15.0.jar
curl --output jsmpp-2.3.11.jar  https://repo1.maven.org/maven2/org/jsmpp/jsmpp/2.3.11/jsmpp-2.3.11.jar
chown jetty:jetty twilio*.jar jsmpp*.jar  ext
cat /opt/gluu/jetty/oxauth/webapps/oxauth.xml


<?xml version="1.0"  encoding="ISO-8859-1"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_9_0.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Set name="contextPath">/oxauth</Set>
	<Set name="war">
		<Property default="." name="jetty.webapps" />/oxauth.war
	</Set>
	<Set name="extractWAR">true</Set>

	<!-- <Set name="extraClasspath"></Set> -->
<Set name="extraClasspath">./custom/libs/twilio-8.15.0.jar,./custom/libs/jsmpp-2.3.11.jar</Set></Configure>
```

**Comment by jgomer2001** [comment]
> So I'm even more confused - why did I find 7.17.0 JAR when the SDK used in build was 7.47.1.

Casa != oxAuth :

Casa is only about enrollments and self service. All libraries used by casa are inside casa.war. So when you enroll a mobile phone, 7.47.1 is in use (or whatever is inside the war package).

oxAuth is only about authentication. When authentication takes place and you are sent an OTP, the libs in `/opt/gluu/jetty/oxauth/custom/libs` are used. Authentication methods are backed by [jython scripts](https://www.gluu.org/docs/gluu-server/admin-guide/custom-script/) and run in the context of oxAuth only.

> Is it OK to replace the included twilio-7.17.0.jar with twilio-8.14.0.jar ? 

Not a good idea. Since  the major version numbers differ, probably the API is not the same or behaviors are different. That may lead to unexpected results.

**Comment by marchharesoftware** [comment]
yeah, OK, that makes sense. I keep forgetting casa is a stand alone application.

I was able to upgrade the twilio jar in the casa.war a little, but not much, and it didn't resolve the problem.  I'm guessing that eventually the dependencies start needing replacing and then dependencies depend on other dependencies... Too hard to do manually.

OK - rebuilding casa with the changes (prepend +), or duplicating the extension is the only way forward... 

It was worth trying, just to see if there was a workaround.

Do you have a policy on how often you upgrade the twilio libraries in the distribution?  the casa one seems to have been current at about the time of the last casa release, but the oxauth twilio library is very very old.  Just curious I guess.

**Comment by marchharesoftware** [comment]
BTW - while I have your attention.  Any tips on setting up building casa from source?  what IDE are you using and what version?  What JDK?  I know I should be able to choose whatever, but just to make my life easier I'd like to pick something which is known to be working...

Thanks!

**Comment by jgomer2001** [comment]
> Do you have a policy on how often ..

No. Most authn scripts and their related assets (ui templates, js, jar files, etc.) are intended to showcase functionality. In practice most people do customizations to suit their needs. Unless security vulnerabilities are detected, this lib is not updated frequently

> Any tips on setting up building casa from source

None beyond the steps you may find in the docs. Known to work: IntelliJ/Eclipe with JDK 8. Different tooling should work.
